module.exports = {
    SC_IS_PROFILE_NAME: "프로필",
    SC_IS_AGENT_NAME: "에이전트",
    SC_IS_CAMP_NAME: "소속",
    SC_IS_CHECK_IN_NAME: "출석체크",
    SC_IS_FOOD_NAME: "음식",
    SC_IS_INFO_NAME: "정보",
    SC_IS_PICK_UP_NAME: "픽업",
    SC_IS_REGISTER_NAME: "가입",
    SC_IS_SETTING_NAME: "설정",
    SC_IS_UNREGISTER_NAME: "탈퇴",
    SC_IS_YOUTUBE_NAME: "유튜브",
    MIYABI_COLOR: "#4ba3ad",
    DANGER_COLOR: "#ff5d5d",
    ICON_BANG_BU: "<:_:1086580894447435826>",
    ICON_QUESTION_MARK: "<:_:1086276872658223165>",
    ICON_BLUE_EXCLAMATION: "<:_:1086276874138832969>",
    ICON_RED_EXCLAMATION: "<:_:1086276876818976821>",
    ICON_MIC: "<:_:1081553033835597854>",
    ICON_DANGER: "<:_:1086276880031817760>",
    YT_NOTIFIE_0: "사용 안 함",
    YT_NOTIFIE_1: "To. 로프꾼, 영상이 올라왔어. 얼른 봐주세... 봐.",
    YT_NOTIFIE_2: "불러서 미안, 하지만 새로운 영상인데 놓칠 순 없잖아? 안 그래?",
    YT_NOTIFIE_3: "새로운 업무 브리핑이 업로드됐네요. 영상이요? 이거 업무 브리핑 아니었나요?",
    PROFILE_PREVIEW: "프로필 미리보기",
    PROFILE_LOOKUP: "프로필 조회",
    PROFILE_REGIST: "서비스 가입",
    PROFILE_AUTH: "연동 여부",
    PROFILE_NAME: "이름",
    PROFILE_UID: "UID",
    PROFILE_REGION: "지역",
    SETTING_ZZZ_AUTH: "ZZZ 연동",
    SETTING_REQUIRED_VALUE: "필요한 값",
    SETTING_PROFILE_INTRODUCE: "프로필 설정 : 소개",
    SETTING_SELF_INTRODUCE: "너에 대해 소개해봐.",
    AGENT_NAME: "이름",
    AGENT_GENDER: "성별",
    AGENT_BIRTHDAY: "생일",
    AGENT_CAMP: "소속",
    AGENT_ELEMENT: "공격 속성",
    AGENT_DAMAGE: "공격 피해",
    AGENT_BASIC_INFO: "—기본 정보",
    AGENT_BATTLE_INFO: "—전투 정보",
    AGENT_IAI_INFO: "—인터뷰 & 소개 정보",
    AGENT_EX_INDICATOR: "예시 지표",
    AGENT_MAX_LEVEL_CRITERIA: "캐릭터 레벨: 100(만랩)",
    AGENT_NECESSARY_ITEM: "필요한 재화",
    AGENT_ARCHIVE: "에이전트 파일",
    AGENT_MATERIALS: "승진 허가장",
    AGENT_COMPARE: "능력치 비교",
    AGENT_TIER_ORDER: "파티 추천 티어는 1st, 2nd, 3rd 순이야.",
    AGENT_TIER_1ST: "1st",
    AGENT_TIER_2ND: "2nd",
    AGENT_TIER_3RD: "3rd",
    AGENT_INFO: "정보",
    AGENT_STATS: "스텟",
    AGENT_BASIC_ATK: "기본공격",
    AGENT_SPECIAL_ATK: "특수공격",
    AGENT_COMBO_ATK: "연계 공격",
    AGENT_DODGE: "회피",
    AGENT_TALENT: "특성",
    AGENT_RECOMMENDED_PARTY: "추천 파티",
    AGENT_OPTION: "에이전트 옵션을 선택해.",
    SETTING_REGISTRATION_DOCUMENT: [
        "**흠? 가입하고 싶다고?\n좋아, 플랫폼에 맞게 영상을 시청하고 값들을 알맞게 입력해서 주면 돼.\n만약에 궁금한 게 생기면 아래에 링크된 서포터 서버로 가서 문의하도록 해.**\n",
        "**아 맞아. 쿠키에 대해 알고 있어? 마침 나한테 쿠키 사용에 대한 서류가 있는데 다 읽어보는 게 좋을 거야. 꽤 중요한 내용이거든.**\n",
        "**```\n1. 쿠키란 무엇인가요?\n```** **쿠키란 웹사이트 접속 시 로프꾼(사용자)의 디바이스와 웹사이트 이용 정보를 수집 및 저장되는 것입니다.**\n",
        "**```\n2. Miyabi는 제 쿠키가 있어야 하는 이유가 무엇인가요?\n```** **Miyabi는 HoYoLAB을 통해 연동(게임 내 정보 불러오기), 자동 출석 체크 같은 간편 기능을 제공하기 위함입니다.**\n",
        "**```\n3. 제 쿠키를 악용할 수도 있지 않나요?\n```** **로프꾼 분들이 조금이라도 더 안전하고 편하시도록 최소한의 정보만 수집하는 방식을 선호하고 있으며, Miyabi에게 쿠키값을 줄지는 여러분들의 믿음에 따라 다르겠지만, 개발에 수 백시간을 넘게 들였으며, 쿠키로 뭔가 딱히 할 게 없습니다. 이익을 위해 쿠키값을 넘기거나 발설하거나 사적으로, 테스트로 등의 이유로 사용하지 않으며, 정보 확인 외엔 일절 사용되지 않으며 정보를 확인할 수 있는 사람은 개발자 한 명뿐입니다.**\n",
        "**```\n가입 이후에 계정이 해킹당하시거나 계정과 관련한 무언가 문제가 발생하는 경우는 불법 프로그램, 레지스트리(클라이언트 변조), 개인 디바이스의 보안 이슈 등으로 인한 것이며, Miyabi와 아무런 관련이 없으며, 책임이 없는 점을 안내해 드립니다.\n```**"
    ],
    SETTING_ADD_OPTIONS: "추가 옵션을 선택해.",
    SETTING_RMV_OPTIONS: "제거 옵션을 선택해.",
    STATS_CALCULATOR: "계산할 스텟을 선택해.",
    NONE: "없음",
    USED: "사용 중",
    UNUSED: "사용 안 함",
    UNKNOWN: "알 수 없음",
    RETCODE_ZERO: "등록 여부를 조사해봤는데 아무도 일치하지 않았어.",
    MISMATCHED_DATA: "{user}의 데이터를 확인할 수 없어.",
    SRC_ISSUE: "다시 시도해 보거나 개발자한테 물어보는 게 좋을 것 같아",
    CAMP_GENTLE: "교활한 토끼굴",
    CAMP_VICTORIA: "빅토리아 하우스키핑",
    CAMP_BELOBOG: "벨로보그 중공업",
    CAMP_SECTION: "대공동 6과",
    ANBY_DEMARA: "엔비 데마라",
    NICOLE_DEMARA: "니콜 데마라",
    BILLY_KID: "빌리 키드",
    NEKOMIYA_MANA: "네코미야 마나",
    SOLDIER_11: "11호",
    CORIN_WICKES: "코린 위크스",
    VON_LYCAON: "본 리카온",
    ANTON_IVANOV: "안톤 이바노프",
    KOLEDA_BELOBOG: "콜레다 벨로보그",
    BEN_BIGGER: "벤 비거",
    SOUKAKU: "소우카쿠",
    HOSHIMI_MIYABI: "호시미 미야비",
    HP: "HP",
    ATK: "공격력",
    DEF: "방어력",
    HP_PERCENT: "HP%",
    ATK_PERCENT: "공격력%",
    DEF_PERCENT: "방어력%",
    IMPACT: "충격력",
    CRITICAL_RATE: "치명타 확률",
    CRITICAL_DMG: "치명타 피해",
    PENETRATION_RATIO: "관통률",
    PENETRATION: "관통수치",
    ENERGY_RECOVERY: "에너지 자동 회복",
    INFLECTING_DMG: "가하는 속성 피해",
    ENERGY_RECOVERY_SPD_PERCENT: "에너지 자동 회복 속도%",
};